GET http://localhost:3001/links

###
GET http://localhost:3001/links/63ab271eb11bdb68f8ee4eda

###
POST http://localhost:3001/links
Content-Type: application/json

{
    "name" : "test",
    "link": "https://www.npmjs.com/package/get-url-title"
}

###
DELETE http://localhost:3001/links/63ab2747b11bdb68f8ee4edd

###
PATCH http://localhost:3001/links/63ab271eb11bdb68f8ee4eda
Content-Type: application/json

{
    "isRead": true
}

### 
GET https://mongoosejs.com/docs/index.html


blabla