GET http://localhost:3001/links

###
GET http://localhost:3001/links/63ab271eb11bdb68f8ee4eda

###
POST http://localhost:3001/links
Content-Type: application/json

{
    "link": "https://www.npmjs.com/package/get-url-title"
}

###
DELETE http://localhost:3001/links/6460eebce02018aca549b401

###
PATCH http://localhost:3001/links/63ab271eb11bdb68f8ee4eda
Content-Type: application/json

{
    "isRead": true
}

###
GET http://localhost:3001/links/4/shuffle

###
POST http://localhost:3001/links
Content-Type: application/json

{
    "link": "https://www.leetcode.com",
    "title": "leetcode_tests"
}

###